apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
    name: cnn-captioning-training
    namespace: kubeflow
spec:
    pytorchReplicaSpecs:
        Master:
            replicas: 1
            restartPolicy: OnFailure
            template:
                spec:
                    serviceAccountName: gcs-access # service account to write to GCS
                    containers:
                        - name: pytorch
                          image: ariearya/cnn-captioning-image-training:v1
                          imagePullPolicy: Always
                          command:
                              - "python"
                              - "train.py"
                          resources:
                              limits:
                                  nvidia.com/gpu: 1 # Request 1 GPU
