apiVersion: apps/v1
kind: Deployment
metadata:
    name: cnn-captioning-inference
    labels:
        app: cnn-captioning-inference
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cnn-captioning-inference
    template:
        metadata:
            labels:
                app: cnn-captioning-inference
        spec:
            containers:
                - name: cnn-captioning-inference
                  image: ariearya/cnn-captioning-image-inference:v3
                  imagePullPolicy: Always
                  # command:
                  #     - "sleep"
                  #     - "infinity"
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: cnn-captioning-inference-service
spec:
    type: LoadBalancer
    selector:
        app: cnn-captioning-inference
    ports:
        - port: 80
          targetPort: 8080
